### ISSUE TITLE
improve search result preview

### ISSUE THREAD

**Issue by SebuLeugger** [veganaut/veganaut#101]
The search result preview should be improved to always show at least the city, not only the street (recently a user added a restaurant which actually is at the "rue la fayette 85" in Paris, but since this adress exists (among other places) also in La-Roche-sur-Yon near the coast of the Atlantic ocean and since our search preview only reads "rue la fayette, France" and if you click on that it takes you to a zoom level at which you don't see that you're not in Paris, but tnear the atlantic ocea instead, the restaurant was placed in La-Roche-sur-Yon by mistake. 

The preview should read, at least: "rue la fayette, paris, france".

**Comment by toebu** [comment]
We use the OSM Nominatim service for the search: http://wiki.openstreetmap.org/wiki/Nominatim. We have to analyse their data model more exactly to be able to make sure we always display the info we want.
The difficulty lies in the fact that there are many different types of locations that it returns, and all the locations have different fields.
