### ISSUE TITLE
More info in location preview

### ISSUE THREAD

**Issue by SebuLeugger** [veganaut/veganaut#106]
This issue should only be tackled once issues #80 and #95 are done.

The small location preview that pops up when users click on a location-dot on the map should show more information. 

1) Top-most line: next to the name of the location (i.e. on the same line) there should be two icons: 
- the average offerQuality rating (the tree symbol inside the team-colored dot) 
- the average effortValue rating (the weather symbol, black on white)

The name of the location (which now still has the colour of the team that currently owns it) should be in standard colour instead (i.e. black).

2) second line from the top: 

- the location type symbol (gastronomy or retail, black on white), without text (now it has text in addtion to the symbol and is in a grey button-like thingy. This has to go.)
- the name of the vegan option available at this location that has the highest rank (if any vegan options have been entered at this location)
- the star-rating of that option (if it has one)

3) bottom line: the points-by-teams display and the "check it out"-button (maybe without text if there's not enough space)

If this doesn't look good, shuffle the elements around a bit.

**Comment by toebu** [comment]
How about showing the total number of products available at the location instead of the top rated product?
