### ISSUE TITLE
Website field doesn't accept addresses without "http://"

### ISSUE THREAD

**Issue by filodoofus** [veganaut/veganaut#109]
I just wanted to edit a location and add a website. I was confused that I couldn't save the edits I made until I realised that the website field apparently doesn't accept addresses without "http://". Is that intentional?

**Comment by toebu** [comment]
It's the default behaviour of our framework if you tell it you want a URL. Not very ideal for the user, I agree. Especially when we are not showing an error message. Will have to be improved.
