### ISSUE TITLE
Editing location = a mission

### ISSUE THREAD

**Issue by SebuLeugger** [veganaut/veganaut#110]
Should we turn the action of editing a location into a mission? The flow wouldn't have to change for that (i.e. it wouldn't have to be listed as a mission; adding a location isn't listed there either but it's still a mission)

pro: 
- more motivation for users to edit and update the location details
- the edit-missions would contain an edit history, which can be used for many purposes
- the edit history could be especially important to retrieve the last good version of the location details if some user who turned out to be a troll deleted or changed the details in an act of trollololo.
- if location details have been changed/added recently the location would pop up in the "recent activity" filter. 

con:
- it's work. 
- it's not strictly necessary. 
- it could be abused by power gamers, unless we either disable it for a few days/weeks for a user who has just edited the location (bad idea, I think), or unless we don't award any more points to the same user for some time after she edited it once (better, but not consistent with how we handle the other missions. But that's maybe not a problem at all.)

**Comment by filodoofus** [comment]
I thought about this as well and have only one thing to add to the pro side: it could flow into the person model (see #96 ).

**Comment by SebuLeugger** [comment]
I think we should definitely make a mission or missions out of editing a location, if only to have an edit history that we can use to restore the location coordinates or descriptions or names after a troll has wrecked havoc on the site.

**Comment by SebuLeugger** [comment]
This has high priority now, since we have a lot more users and the likelihood that someobdy wreaks havoc in the location descriptions (intentionally or by accident) has gone up. If you can, please either make backups of our database daily or implement this issue (and don't forget to save all the current descriptions and homepage-links of locations as missions (you can pick an admin/NPC as their author, doesn't matter)

**Comment by SebuLeugger** [comment]
![imag0780](https://cloud.githubusercontent.com/assets/6586945/7889006/e6df9002-063c-11e5-8d39-047034d057da.jpg)

**Comment by alesiom** [comment]
1) Example when user is not connected.
![detail_page_disconnected](https://cloud.githubusercontent.com/assets/5433764/8272788/66ffbb6a-1851-11e5-8a93-a556cf6d420a.png)

2) Example when user is not connected and scrolled down.
![detail_page_disconnected_scrolled](https://cloud.githubusercontent.com/assets/5433764/8272789/6705cafa-1851-11e5-9ab6-e56c2f804c8e.png)

3) Example when user is connected. (Notice that the "edit" icon is outdated, check point 5 and 6 for an uptodate version)
![detail_page_connected](https://cloud.githubusercontent.com/assets/5433764/8272786/66ff3aaa-1851-11e5-9b57-bfe89acc1e30.png)

4) Example when user is connected and some of the entries are not editable
![detail_page_connected_noedit](https://cloud.githubusercontent.com/assets/5433764/8272785/66fb9558-1851-11e5-8ba5-061d8ef80cd8.png)

5) Example when user is connected and has some mission (I advise to always show a mission on top of the food list). Invite the user to act.
![detail_page_connected_missions](https://cloud.githubusercontent.com/assets/5433764/8272784/66d66df0-1851-11e5-91ef-0a41d0f133ec.png)

6) Example when user is connected and a comparison with "Koala", the user that "wins" currently this location. The bar is a loading bar. If the user acts below, the bar is updated to enhance the feeling of gaming and competition. 
![detail_page_vskoala](https://cloud.githubusercontent.com/assets/5433764/8272819/c3948d0a-1852-11e5-8065-3b336a984c3d.png)

7) Example when user is connected and wants to update/grade/etc some food entry. Notice that the information block can be larger (e.g. description of the product, "unavailable for the moment, etc). Also, there can be more than one action, they are just listed one underneath the other. The total points that the user can get should be shown in the right icon when the food entry is collapsed.
![detail_page_updatefood](https://cloud.githubusercontent.com/assets/5433764/8272787/66ff5ca6-1851-11e5-963b-58ce58ca65e0.png)

**Comment by SebuLeugger** [comment]
obsolete
