### ISSUE TITLE
Design: make all list (and button?) backgrounds semi-transparent

### ISSUE THREAD

**Issue by SebuLeugger** [veganaut/veganaut#113]
The background of lists (especially the one in the product browser) should be semi-transparent like all the other white background. 

Maybe the background of the buttons as well as the text entry fields should be semi-transparent as well? I don't know. Designers decide.

**Comment by SebuLeugger** [comment]
The list is done, what about the buttons?

**Comment by toebu** [comment]
I think we are good here. This is a detail and can be considered when we work more fundamentally on the design.
