### ISSUE TITLE
Search the map: find veganaut-locations also

### ISSUE THREAD

**Issue by SebuLeugger** [veganaut/veganaut#114]
Dirk Tas suggested, and I agree, that users will take it for granted that when they search the map for a location the system will find veganaut-locations, i.e. the gastronomy or shopping locations added by veganaut users. Currently, the search functionality just finds openstreetmap locations.

I think it's OK in the first version to just show the name of the veganaut-locations as an underlined link (just like the other search results are displayed now). 

In a later version, we should probably add at least the city where the found location is located (i.e. "tibits, Bern"), plus maybe the street (if it's possible to determine that based on our data, i.e. "tibits, Gurtengasse, Bern"). Later we could also add things like the offerQuality symbol or maybe even some sort of expandable preview (but probably not).

**Comment by SebuLeugger** [comment]
clicking on a link to a veganaut location in the search form takes you back to the map, with the location in the centre of the map and selected (i.e. the preview is open and the location dot on the map is highlighted (i.e. opacity 1, a bit bigger than normal, thicker white border than normal)

**Comment by kremated** [comment]
Upvoting this, probably the most important improvement for me at the moment.

**Comment by SebuLeugger** [comment]
This is how we think we want to do it:

The search symbol is in the topmost menu bar (which might at some point be the only menu bar):

Clicking on the search symbol opens a text field within the topmost menu bar (i.e. the veganaut-logo disappears on mobiles, maybe also the burger).

Typing in that text field opens a preview of the search results (overlay) below the topmost menu bar, which is structured as follows:

- first, a heading which says "veganaut locations", with maybe the top three search results (just the name of the location, plus maybe something else, anyway, just plain text in link-styling, not a preview or the like)

- then, a heading which says "products/offers" or the like, with also a preview of maybe three products that match the search query

- then, a heading which says: "map" with three places on the openstreetmap that match the query.

Under or next to each of these headings there's a button which says "show more". clicking this button takes you to a new page, the search page, showing more search results under that heading (the other headings could be either minimized or just as before)

**Comment by toebu** [comment]
A first version of this is finished and live!
