### ISSUE TITLE
Add location type icons to filter buttons

### ISSUE THREAD

**Issue by SebuLeugger** [veganaut/veganaut#121]
what it says in the title

**Comment by toebu** [comment]
The filter buttons for the location types should have the icons like this (keeping of course the option "both" with no icon):
![screenshot_20161108_172724](https://cloud.githubusercontent.com/assets/1837568/20107392/b3c90224-a5d8-11e6-9fe6-62b3effe76b7.png)

**Comment by toebu** [comment]
This was fixed with #205
