### ISSUE TITLE
Design: find icons for the 4 player attributes

### ISSUE THREAD

**Issue by SebuLeugger** [veganaut/veganaut#132]
We need icons to symbolise the 4 player attributes. Here's my first suggestion: 

- pioneer: a compass
- diplomat: one or two overlapping speech bubbles
- evaluator: an eye, or a star (like the star in the ratings)
- gourmet: a chef's hat (but maybe we better save that one for when we introduce recipes and with them a "chef" attribute), or one of those plates with a fancy haute-cuisne cover (see the icon below the chef's hat here: http://static.vecteezy.com/system/resources/previews/000/081/785/original/large_restauranticons.jpg )

**Comment by filodoofus** [comment]
Here are some icons from fontawesome (http://fortawesome.github.io/Font-Awesome/icons/) which can be implemented as a webfont (open source):
*  pioneer: http://fortawesome.github.io/Font-Awesome/icon/compass or http://fortawesome.github.io/Font-Awesome/icon/globe
* diplomat: http://fortawesome.github.io/Font-Awesome/icon/comments or http://fortawesome.github.io/Font-Awesome/icon/comments-o
* evaluator: http://fortawesome.github.io/Font-Awesome/icon/eye or http://fortawesome.github.io/Font-Awesome/icon/star or http://fortawesome.github.io/Font-Awesome/icon/tags or http://fortawesome.github.io/Font-Awesome/icon/tasks
* gourmet: http://fortawesome.github.io/Font-Awesome/icon/cutlery

**Comment by SebuLeugger** [comment]
Nice. There's also the bootstrap components http://getbootstrap.com/components/ (check out the eye and the stars e.g.) which we already use for a lot of icons.

**Comment by SebuLeugger** [comment]
It looks like we'll be getting rid of the player attributes, so this issue is no longer a thing.
