### ISSUE TITLE
Design: still show filtered-out locations, but very faded?

### ISSUE THREAD

**Issue by SebuLeugger** [veganaut/veganaut#136]
Yesterday we thought that maybe it would be a good idea to never fully hide the locations that are filtered out, but instead to just fade them a lot, such that they're still visible in a ghostly way. 

One idea was to make the faded locations unclickable, but I think they should function like normal. As I think of it, the filter would just be a visual aid that helps the user focus on / see what she is initially mainly interested in, but not something that keeps her from changing plans midway and from seamlessly focusing / checking out something else instead.

The main reason why I think this would be a good idea (it's not any of the ones we discussed yesterday) is that in this way, all locations always stay visible, which makes the way the product browser 
works more intuitive. (The product browser always gathers all the options available at all the locations in the given map section, no matter whether they are filtered out or not. That doesn't make a lot of intuitive sense If filtered out locations are invisible.)

I think we should do this. However, it has to work visually, and I don't know whether it does. Thus the questionmark in the title of this issue.

**Comment by SebuLeugger** [comment]
Another reason why this might be a good idea: Once we have implemented #114 we have to decide what to do when users click on a veganaut location link in the search resulst. A bad decision, in my opinion, would be to go directly to the location details view - I'm on the map and I did a map search, so I want to see the result of my search on the map. So a better decision is to show the veganaut location on the map. But how? Of course, we could just zoom in maximally. But even so, some location dots may be very close togehter and it may not be obvious which dot is in the center of the screen. The obvious solution is to filter out all other locations. But if all filtered-out locations are now invisible this really limits my map-browsing experience. OK, I may have wanted to know where that one location was, but that doesn't mean I don't want to see any other locations nearby. - Sure, there would have to be a way to unfilter the map again either way (how would we do that?), but if the other locations are still visible I don't have to unfilter the map before I go on browsing the map, and in many or most cases, that's good enough.

**Comment by SebuLeugger** [comment]
Similar to the above reason (cf. the second comment of #83): we'll want to show our users all the locations where they can get a particular product (that is available at more than one location), and filtering out all the location where it isn't available is a great way to do so. However, as before, we don't want to keep users from seamlessly changing their focus midway and browse the map for something else instead.

**Comment by SebuLeugger** [comment]
since we'll use opacity to stand for offerQuality it's a bad idea to also use it to filter/highlight stuff on the map. What we can do instead is discolor the filtered-out locations, i.e. make them grey.

**Comment by toebu** [comment]
![greyedoutlocations](https://cloud.githubusercontent.com/assets/1837568/6996940/63f12f04-dba6-11e4-8194-8eeb1d1fd4b5.png)
Here a suggestion of how the filtered out locations might look like. I would make them in a way that you cannot interact with them at all. Hovering doesn't change the style, clicking them is treated like clicking the map.

**Comment by SebuLeugger** [comment]
Looks great!

Let's talk about our respective reasons for and against being able to interact with filtered-out locations. I agree that if they are that small and don't have any icon in them it doesn't make a lot of sense to make them interactive. But why not JUST make them grey and don't change them in any other way, i.e. keep the symbols and the sizes and the opacities and the interactivity? - Maybe I see the reason when I see a mockup of this suggestion, or maybe you can explain it to me verbally. Anyway, I think your suggestion would certainly work.

**Comment by toebu** [comment]
![greyedoutlocations2](https://cloud.githubusercontent.com/assets/1837568/6997251/4a6b015e-dbb5-11e4-8f02-3db059db8d73.png)
Here is how it looks like in grey and moved behind all the locations that are not filtered out.
For me it's too messy and doesn't show well enough that these places are filtered out. If I'm using the filter, I'm saying that I don't care about the other places, so why are you still showing them to me and making me click them (by mistake)?

Yeah, let's talk f2f if you don't agree.

**Comment by SebuLeugger** [comment]
This second version does look too crowded, I agree. I think we have to talk about the most important use cases for filters and decide based on this. Let's wait for feedbacks to our next version of the platform and take it from there.

**Comment by SebuLeugger** [comment]
Maybe if we think of the whole thing not as filtering, but as *highlighting* (and if we changed all the icons and texts on the platform accordingly, e.g. instead of this funnel-thingy we use a highlighting pen as a symbol (cf. http://www2.psd100.com/ppp/2013/09/2601/chisel-tip-marker-icon-0926020027.png ) and we write "highlight recent activty", "highlight according to location type",...) and if for the location dots on the map we choose something in between the first and the second version above... maybe then we have an ideal solution: everything that is not highlighted is grey, small and very transparent, but still features a symbol and is clickable, and nobody would expect otherwise, because those grey locations are not filtered out, but merely not highlighted.

**Comment by SebuLeugger** [comment]
Since you already implemented the first version we maybe want to use this code anyway. Why not have two modes of using the filters: as filters or merely as highlighters? - there could be use cases for both, I guess.

**Comment by toebu** [comment]
I think it's definitely too complicated to keep both modes. We don't need more options, we already have enough of those for the different filter settings.

For no, I'm just kept the locations that are filtered out completely hidden (as before). It will be a small effort to get to any of the above pictured solutions.

Our main problem with the filtering is the following: Once we include the filter settings in the URL, someone can get on the page and not know that not everything is shown. The first version with the very small grey dots probably doesn't help with this. The second picture above with the greyed out locations would certainly alleviate that problem, but I think it defeats the purpose of filtering locations in the first place (which is bringing focus to what you really want to see).
Instead, I would introduce a new small button/link (for example at the top right below the filter button but within the map), that says something like "Show all locations". Clicking it would reset all the filters. Or one could only show that button if the user clicked on one of the mysterious grey dots, and have it disappear after a few seconds if not used. Or yet another way of styling it: simply have a same kind of grey dot in the button. One could even keep it around as a toggle to turn filtering on/off.

There's certainly other ways of styling this, but the main idea would be to have a new link to unset all the filters that is outside the filter menu.

**Comment by SebuLeugger** [comment]
obsolete
