### ISSUE TITLE
merge search and filter buttons?

### ISSUE THREAD

**Issue by SebuLeugger** [veganaut/veganaut#137]
This #136 got me thinking: Should we merge the search and filter buttons / functions into one? I think it would make intuitive sense, it would get rid of the filter-icon in the map menu which most people don't understand anyway and thus aren't likely to click, and it would free up space in the menu for another button.

How would this look like? Well, just add the filter options below or above the search form (maybe it should be possible to minimize them separately).

If one or more filters are active the button could still look pushed, even if its symbol is a magnifying glass instead of a - well, the symbol isn't even a filter now, it's a funnel. Or maybe that wouldn't be intuitively clear enough. - Hm, I don't know what's best. 

Anyway, the reason why I thought it would be a good idea to merge the two functions was that I thought it could make sense to filter the map in a particular way based on a search result - and then the question comes up how to unfilter the map again after that. As it is, only the filter-function has a "memory" that survives e.g. the opening of a location preview or indeed even moving away from the map to the teams view and coming back again, while the search-function has no memory at all. And even if it had a memory, it would still be strange to unfilter the map by doing something in the search form instead of the filter form. So let's just make those two forms one, and the problem is solved.

**Comment by SebuLeugger** [comment]
If we anyway also allow the product browser to filter the map (cf. towards the bottom of the second comment of #83) we may just as well also allow the search function to filter it, and do so even if it's not merged with the "official" filter function. However, it's not trivial how to combine all this. If the offical filter functions filters particular locations out (e.g. shops, because the filter is set to highlight gastronomy locations), but then the search function wants to show some particular shop on the map, which filtering wins? The most logical solution would be: the latest filtering wins. But does it delete the previous filtering, or does it merely deactivate it temporarily (such that when the search-filtering is deleted the original filter-filtering is again put in place)? - Maybe integrating the two functions enables us to solve this problem in the most intuitive and transparent way: Just show users a toggle-switch of some kind, which makes it clear that you can either filter the map by using the filter buttons, or by using the search, but not both at once. When the search filters the map, the filter settings are not reset, but they are deactivated (e.g. grey instead of black), and when the filter filters the map the search looks deactivated (grey instead of black).

This does not solve the analogous issue with the product browser yet. Then again, maybe it does. If the filter/search button actively filters the map, that button appears black instead of white. If we now open the product browser and then somehow use it to filter the map, the previously black search/filter button just turns to grey, indicating that it's no longer actively filtering the map. The product browser button, in turn, is now black (which also means that it needs a "memory", I guess), indicating that it is actively doing something on the map atm. If I now click on the search/filter button the search/filter menu opens again and I can activate whatever filter I want there. Two possibilities: 

1. I delete all search/filter-filterings and close the search/filter menu: the search/filter button is now white.
2. I choose some search/filter filtering and close the search/filter menu: the search/filter button is now black. 

In case 2. the product browser button now has to be grey. In case 1. it could be either black or grey. Either could make sense, but I think it makes more sense if it's grey, i.e. inactive. It's more likely that by deleting all the filters in the search/filter menu I wanted to unfilter the whole map (and not just remove filterings that weren't active anyway). 

If I click again on a black or grey product browser button, I should see what I saw when I left the product browser, and  there should be a way to undo the filtering and turn thus turn the product browser button back to white again.

**Comment by SebuLeugger** [comment]
OK, so let's take this to its logical conclusion: Why not integrate all three into single menu: the search, the filter AND the product browser? 

PRO: 
- nobody intuitively understands the leaf-symbol anyway
- the product browser is a kind of search anyway, and it can also be used to filter the map
- even more space for other buttons in the main map menu
- all the filters (even the ones we haven't implemented yet) make sense for the products as well (especially the location type filter)
- ...

CON:
- the serach/filter/products menu may get cluttered
- some filters may not make the same sense for the locations as for the products (recency filter especially)
- ...

How could it look like & work? Well, underneath the search field and the filter buttons, just add a section entitled "products available in this map section" with a button "search for products". Pushing that button minimizes the search field (but leaves the filter buttons visible) and opens a list of products, like it does now. This list can now be filtered with the filter buttons. Plus there might appear an "order list" menu which lets you order the list in different ways. But maybe not.

**Comment by SebuLeugger** [comment]
Idea: since the recency filter is somehow awkward in the above scenario with the integrated product browser, and since that filter could anyway cause problems when we want to create shareable links because it's so dynamic, and since we might have more space in the main map menu, and since it may make sense independently of all of this, let's think about this:

Maybe we want to separate all the ways to explore the more static aspects of the map/locations/products from the ways to explore the more dynamic aspects: have one button for exploring the static aspects (search, filter, browse products), and one button to learn about what's new / what happened recently (new locations, new products etc.). I think those two buttons would serve pretty distinct interests / use cases and it makes sense to separate them. 

So, concretely, we would no longer have the recency filter in the same menu as the location type or offerQuality filter. (They are seldomly combined anyway; at least I never combine them. I just look for what's new, not for what's new in terms of restaurants but not shops. But anyway, combining them would not be excluded by not having them in the same menu. They could still be combined, I guess. But maybe we wouldn't allow it because it makes things murky. I can't tell yet.) Instead, the recency filter would be in a separate menu, together with its own product browser button which says: "show newly added products in this map section"; how newly the products have to be added to appear on the list would be determined by the recency filter setting. (the news-menu wouldn't have a search field; I can't think of a use for that there).

Maybe that's a stupid idea. Especially in the product browser I imagine I'd still want to filter the recently added products for gastro vs. shopping, so the news menu might end up with pretty much the exact same buttons as the static search/browse menu. Then again, it's the small differences that might make these two menus valuable. I can't tell.

Let's keep this in the back of our minds for now.

**Comment by toebu** [comment]
I think we have a pretty good idea by now how we'll want to do this. I'm closing it. @SebuLeugger re-open if you don't agree.
