### ISSUE TITLE
Jump-starting the game in new regions

### ISSUE THREAD

**Issue by SebuLeugger** [veganaut/veganaut#143]
In order to jump-start the game in regions where no or hardly any veganauts have been active yet we should do the following:

- add all (or at least many or most of) the locations with vegan offers that are already listed somewhere (especially on the local vegan/vegetarian groups' and societies' homepages) - otherwise the people active in these groups will feel like participating on veganaut.net has no added benefit for them / that veganaut.net is useless / that it just requires work which they have already done.

- add the locations in a way that makes it interesting for people active in that region to start playing the game - if e.g. all the added locations belong to one team it may be disheartening for players of all the other teams, and if the locations belong to different teams pretty much at random it may be disengaging: the teams don't mean anything if they're not filled with actual people who are active in that region but instead just some random colours on a map. 

Therefore, I think it would be good to add a neutral "team" with a neutral colour (e.g. grey/brown), for which there are several uses (cf. https://github.com/veganaut/veganaut/issues/32#issuecomment-85927442 ), but for now it would be simply for adding and editing large numbers of locations in regions where we are not actually active at.

**Comment by SebuLeugger** [comment]
If we do it as described above we have to make sure somehow that new users get that they can and should add pretty much every restaurant or shop that has or might have vegan options, not just the ones which already have a good vegan offer. - Up to now, most lists on most vegan societies homepages focus on locations with what would be a high offerQuality rating on veganaut.net - Somehow we have to get it accross to them that having lots of locations with lower offerQuality ratings on the map is valuable as well and encourage them to add locations that they wouldn't have put on their lists. - Maybe this problem solves itself, but I think we should jump-start that as well.

**Comment by toebu** [comment]
Done! NPCs work in the following way now:
- They are normal accounts with which one can do everything on the platform.
- You never receive points for missions (if if the frontend shows the points in the mission list).
- NPCs are never listed on the score page or on the recently active veganauts list. Profiles of NPCs cannot be fetched (except for profile/me).
- To create an NPC, one has to change the team to 'npc' directly in the database.
