### ISSUE TITLE
make map links more human-readable?

### ISSUE THREAD

**Issue by SebuLeugger** [veganaut/veganaut#146]
Currently, a map link ends as follows: .../map#46.1570050,8.4704590,7 with the first two (long) numbers being the coordinates and the number behind the last coma being the zoom level. Since links with lots of inscrutable numbers in them look scary (at least to me) and people are less likely to click them (at least I am), especially if the link is to a page I don't know, and since one of the main purposes of sharing veganaut map links is to get people to visit the site who don't know it yet, I think it would be great if map links could look like this instead:

 .../map@zoom7,coordinates46.1570050,8.4704590

(And later more or less like so:  .../map@zoom7,coordinates46.1570050,8.4704590,filters3,6,10 )

Maybe that's a stupid idea, or it's too much work. If it's neither I think we should do it.

**Comment by toebu** [comment]
Can do. Just once we settled for a format, we should stick to it (otherwise old links will break or we'll have to keep legacy formats around to try and parse those too).

I wouldn't use exactly the format you proposed, but something more human readable can be done.

**Comment by SebuLeugger** [comment]
Cool. I think it would be ideal if the scariest, i.e. longest numbers, i.e. the coordinates are in the middle, because then I understand the first (e.g. zoom) and the last (e.g. filter) number, so it doesn't matter what's in between, psychologically. But you do it however you think is best.

**Comment by toebu** [comment]
I'll make it like this:
/map#zoom=7&lat=14.1234567&lng=9.1234567

Is that human-readable/-friendly enough or are there too many special characters?

**Comment by SebuLeugger** [comment]
That's even scarier than just the numbers, if you ask me. Is it possible without the "=" and the "&"? Also, "lng" looks like "Ing" (i.e. "LNG" looks like "ING")

**Comment by toebu** [comment]
I see.
/map#zoom:7,coords:14.1234567;9.1234567
?
