### ISSUE TITLE
How to show the location type on the map / hide teams / ...

### ISSUE THREAD

**Issue by SebuLeugger** [veganaut/veganaut#147]
Currently, the dots representing locations on the map have the colour of the team owning the location and feature the symbol corresponding to the location's average offerQuality (i.e. a plant with between one and five twigs, or nothing/a questionmark) in white. 

There are a few problems with this:
- people who aren't playing the game don't care about which team owns which location
- people who don't know the site don't know what the offerQuality symbols mean
- people who don't know the site, but also those who do, often are primarily interested in whether a location is a gastronomy or a shopping location than in the location's average offerQuality

These problems suggest that there should be a view of the map that shows the location dots with the gastronomy or shopping symbol inside, and without the colours corresponding to the teams. Let's call this view the non-game mode, and the current one the game mode.

We thought about adding a button or switch which allows users to switch between these two modes. However, we didn't know how exactly to implement the non-game mode. Now I have a good suggestion, I believe:

- in the non-game mode, location dots are white
- in the non-game mode, location dots feature the shopping or the gastronomy symbol
- in the non-game mode, the symbol featured in the location dots are coloured: the gastronomy symbol is e.g. veganaut-turquoise, the shopping-symbol is veganaut-yellow (or some other colours that aren't too close to team colours; however, that's not so important because it's not the colour of the dot we're talking about but the colour of the symbol. Anyway, the two colours I mean are the ones on Spot's design sheet.)

Maybe it will turn out that it doesn't make sense to have two separate modes. Instead, maybe we want to give users the tools to decide for themselves which symbol they want to see inside the dots, and independently whether they want to see the teams or not. We could do this by taking the non-game mode dots as described above and adding a ring around them, the ring's colour corresponding to the team owning the location. However, maybe that will look too ugly or cluttered. Anyway, in any given location dot (which would always be white in this version), the offerQuality symbol could have the colour corresponding to the location type, so e.g. a turquoise plant with five twigs inside a red ring would be a restaurant with the highest average offerQuality belonging to the red team. A yellow plant with three twigs inside a blue ring would be a shopping location with medium offerQuality belonging to the blue team. 

The logical buttons/switches needed for this second version would be:

- show location type symbols / show offerQuality symbols
- show teams / hide teams

The default setting for users who aren't logged in would be [show location type] & [hide teams]. The four combinatorial states could also be implemented within one single button which just goes to the next of the four states in a pre-defined sequence whenever it's pushed: 

1. [show location type] & [hide teams]: *minimum information, visual redundancy (location type coded by symbol & colour), intuitive (location type symbols)*
2. [show offerQuality] & [hide teams]: *more information, no visual redundancy (location type only coded by colour), not intuitive (no location type symbols, unknown offerQuality symbols)*
3. [show offerQuality] & [show teams]: *maximum information, no visual redundancy, not intuitive, cluttered colour-wise*
4. [show location type] & [show teams]: *less information, visual redundancy, intuitive, cluttered clour-wise*

Should users be able to hide the location type, i.e. switch off the colour-coding of the symbols according to location type? Maybe. But maybe not. 

Would we still need the location type and the offerQuality filters if we implemented this second version? I don't know. Maybe not.

**Comment by SebuLeugger** [comment]
(When I assign issues in the sthinking-deciding state to a milestone I don't mean we have to implement them to finish that milestone. I just mean we have to think about them while completing this milestone, and maybe implement them now, or implement them later, or not at all.)

**Comment by SebuLeugger** [comment]
We decided yesterday to do it like this:

- we'll never use colors to stand for anything but the teams (so we won't use it to stand for the location type, for instance)
- the color of the location dot is the color of the team owning that location, the symbol inside the dot is white
- we'll use the size and the opacity of the location dots to stand for the offerQuality (big dots with high opacity means high offerQuality, small dots with low opacity means low offerQuality); the location dots need a 1px white border for this to look nice.
- we'll put the location dots on different z-axis-layers based on their offerQuality. The highest offerQuality goes on top (this way, when you're zoomed out you basically see the "best of", and when you click on a tangle of locations you're most likely to click on the best one)
- by default, we show the location type symbol inside the location dots on the map
- (not part of this issue) later, we'll add radio buttons to the location type, the offerQuality and the effortValue filters in the filter menu: by selecting one of those 3 "dimensions" users can decide which symbols they want to see inside the location dots on the map: the location type symbols, the offerQuality symbols, or the effortValue symbols. Maybe we'll also let users choose to not show any symbols at all, because the multicolored and different sized/transparent dots look really nice without symbols. It's fun to just look at the map like that.

**Comment by toebu** [comment]
This is now done in a first version. I would like to set the marker z-index more precisely (based on the un-rounded average quality, so that a 4.8 is always in front of a 4.5), but this needs Leaflet/Leaflet#3365 to happen before.
