### ISSUE TITLE
List products in alphabetical order

### ISSUE THREAD

**Issue by filodoofus** [veganaut/veganaut#148]
It would be easier for users to find products in the list of available items if the list was ordered alphabetically.

**Comment by SebuLeugger** [comment]
Do you mean the list in the location details view or the one on the map (or both)?

**Comment by filodoofus** [comment]
I think mainly in the location details view. The view on the map might be subject to other restrictions (like ordering in terms of quality or what not).

**Comment by toebu** [comment]
The main list on the location page and the one on the map ("Vegan Menu") are ordered by rating. I would argue that this should stay like this. For the other lists (when adding more options or specifying which ones one bought), it is not ordered alphabetically.
