### ISSUE TITLE
edit product: bugs/inconsistencies

### ISSUE THREAD

**Issue by SebuLeugger** [veganaut/veganaut#166]
Situation: a location with only 1 vegan option (I chose Fass-Beiz in Schaffhausen)

- I edited the availability of the one and only vegan option to "currently not". Here's what happened:
  - the vegan option was still visible in the location details view, only written in gray instead of black. Since there are no options written in black users don't see that this grey option is "less real" than an option which is available. Maybe we should put "(currently unavailable)" in brackets in front of or behind the option name in addition to the grey font?
  - the vegan option I just said is currently unavailable still shows in the location preview on the map. I think the rules for showing currently unavailable options in the location preveiw should be as follows: 1) no currently unavailable option has a higher rank than an available option, no matter their rating, i.e. if there's an available option we see it, even if a currently unavailable option has a higher rating. 2) if a location only has currently unavailable options, then we see the one with the highest rank, but it has to be marked as "currently unavailable", i.e. behind the option name in brackets, and it should be shown in gray font, for consistency.
  - the vegan option I just said is currently unavailable still shows in the product browser for that map section. - The same applies as here as for the location preview: unavailable options have a lower rank than available options and they have to be marked as currently unavailable in brackets and shown in gray. 

- Then I edited the availability of that one option to "No" (i.e. not available any more at all), and here's what happened:
  - in the location details view, I didn't see the option any more at all, and it said that nobody had ever entered an option at this location. However, the option was still listed in the whatOptions mission, but it's not possible to edit it there. Also, the option still showed in the location preview on the map and in the product browser for that map section. I think it should be like this instead: If the location's only vegan option is "not available any more at all", then it should still show that option in the location details view, simply ~~struck through~~. The struck through options don't have to be shown if there are available or only currently unavailable option to display, of course. Also, options which aren't available any more at all shouldn't feature in the location preview or in the product browser at all, I think. It doesn't make sense to show them there. 

Independently of all of this: there should be a button "add another vegan option" at the bottom of the list of options in the location details view. This button can just take you to the whatOptions mission for now, but I think we need that button now more than ever, because people expect to be able to add to the list when they are able to edit individual items, and if they don't find that button there they get confused.

**Comment by toebu** [comment]
Almost all of this has been fixed in the meantime. The same styles are now applied everywhere where products are shown (greyed out for temporarily unavailable, greyed out and struck through for unavailable products).
It's might still be a problem if in a context we only see temporarily unavailable products since we don't have the contrast. For me this is OK since the product might actually be available again in the meantime and in most views one can click on the product and see that it is temporarily unavailable.
