### ISSUE TITLE
Performance improvement

### ISSUE THREAD

**Issue by SebuLeugger** [veganaut/veganaut#167]
On many mobile devices, veganaut.net has gotten so slow that it's almost unusable. Can we only load the locations that are visible in the current map section? I think my phone's working memory is too small to handle all the locations, even if they are loaded "in the background" and I can already interact with the map once only the highest rated locations are loaded (this is the solution we discussed before; I'm unsure whether it would help). Maybe it would also make sense to only load the highest rated location per visible square centimeter on the map (or something like this), especially when you're zoomed out a lot, i.e. only the locations that end up being clickable.

**Comment by toebu** [comment]
This is deployed now, let's see if that's enough for now.
