### ISSUE TITLE
Rewrite the home page

### ISSUE THREAD

**Issue by SebuLeugger** [veganaut/veganaut#171]
Once the teams are gone we need a new text for the home page (in all languages). Also, some users suggested we should add a picture and a short description of the team behind veganaut to the home page, to add a personal touch. I think that might be a good idea. What do you think?

**Comment by SebuLeugger** [comment]
The french translation still has to be done. Otherwise this is finished.

**Comment by toebu** [comment]
I'm closing this, French translation is out of sync in many places and will have to be addressed once as a whole.
