### ISSUE TITLE
dots of ?-locations should be as big & opaque as 3-twig locations

### ISSUE THREAD

**Issue by SebuLeugger** [veganaut/veganaut#172]
Location dots of locations without an offer quality rating are now shown minimally small and opaque. This does not make sense since most of those locations are actually quite good, vegan-wise, and it's just that people didn't bother to rate them. Therefore, I think we should show them as big as 3-twig locations, i.e. with middle size and opacity.

**Comment by toebu** [comment]
One could also do something like this:
![unknownloc](https://cloud.githubusercontent.com/assets/1837568/9875821/93cfbd4a-5bb1-11e5-9d81-ca2b786052c8.png)
