### ISSUE TITLE
Lists!

### ISSUE THREAD

**Issue by SebuLeugger** [veganaut/veganaut#174]
We need lists. Lists are great. They can be ordered, searched and filtered. And they can, in turn, serve as filter criteria for the map: e.g. if I did my research before I go on holiday and I have my list of restaurants that I want to go to it would be great if I could just hit the "show this list of locations on the map"-button and would then be taken to the map with all other locations filtered out. Anyway, that's just me fantasizing. This issue is about something simpler: showing the locations within a given map section as a list (and maybe ordering or searching them).

I don't know the best way to implement this. I just propose one way here: 

The button which is now the "vegan menu" button could become our "lists" button. Everything stays the same as it is now, with only one difference: at the top of the vegan menu there's a button which says: "show list of locations instead". Pushing this button takes you to a list of all the locations in the visible map section, ordered alphabetically or by their offer quality from high to low (show only first 20 locations or so, with "show more" link at the bottom). There could also be a search field at the top of this list, which lets you search among the locations listed (only the names of the locations, not e.g. the products available there; for this, there could be a search field at the top of the vegan menu list) and/or a filter/order-button, which, upon pushing, lets you choose all kinds of ways to filter or order the list. 

If we provide ways to filter the list (narrow it down), then it would be cool to also have a button "show these locations on map" (or, for the vegan menu list: "show locations on map where these products are available") button, which takes you back to the map, with only the locations on the list (...) visible.

**Comment by SebuLeugger** [comment]
Lists are a separate kind of page (not an overlay on the map page).

wenn von karte her kommend: "karten-filter-button" angeklickt: d.h. die liste ist durch einen kartenausschnitt gefiltert. Diesen filter der liste kann man aufheben, dann updated es die liste global. (bzw. nicht durch kartenausschnitt, sondern durch koordinate plus radius; wenn man von der karte her kommt, entspricht dieser radius dem grössten kreis, der noch zur Gänze auf den sichtbaren kartenausschnitt passt)

es gibt auch noch andere listen-filter: shopping vs. restaurant - ev. offerQuality - ev. effortValue

Und dann natürlich noch verschiedene Anordnungs-Optionen: "Nach offerQuality ordnen", "alphabetisch ordnen", "ordnen nach Distanz vom Kartenmittelpunkt" [falls Kartenfilter aktiv] "ordnen nach Distanz von meinem Standort" [wenn man das anklickt, fragt es einen nach erlaubnis, den standort durchzugeben]

**Comment by SebuLeugger** [comment]
Test report: 

buggy stuff:

on the fairphone I used, the home page first loaded properly, then kind of disappeared (only the oppenstreetmap was visible, no veganaut elements), when I clicked around (but maybe not because of it?) the home page stuff flickered on again, and off again, and then I seemed to have managed to click the "to the map" link when it was showing for a short amount of time and I was taken to the normal map view. 

I could not hit any of the buttons in the top bar (the veganaut logo, the login button or the menu button) on the fairphone. I'm also having trouble doing it on the laptop (firefox), I have to move the cursor around quite a lot until it finally changes from the arrow to the index-finger-hand, and only then can I push any of the buttons in the top bar. 

on the fairphone the offerQuality symbol of a lot of locations on the list (but not of the first 10 or 20) was all black, even though I know that they have a rating, so it wasn't because they should have had a questionmark or something. even when I clicked on "more", the offerQuality symbol in the location details view was still all black. On the laptop, I couldn't reproduce this later.


stuff which I assume is due to this being an early version:

the map filters are gone! I assume you will bring them back under the search field. and that you will add filters to the list page.

especially in view of the embedded map which has less space available I would like to suggest again that we merge the "vegan menu" and the "location list" buttons in the way suggested in the original description of this issue. 

there is no "list" menu item in the main menu.

the sequence of location symbols in the list should be: type of lacation (gastronomy/shopping), offerQuality, effortValue

When there are no locations within the radius it should say so: "Oops, no locations were found within the radius chosen."


an idea I had while doing the testing:

In the section of the location preview in the list where now it says "more info to come", what do we want to put there? Besides the best three vegan options available at that location maybe it would be good to show a very small square map with the same radius as the one that defines the list (but obviously with a lower zoom level than the one of the map view I just came from) on which I can see a small red cross or something where that restaurant is on the map, i.e. where it is within the radius chosen. Maybe the radius should be visible on this very small map, i.e. again by that grey circle that is visible for a short time before the map loads, so as to teach users what that circle means. 


Something that was not clear to me: 

When I went to the map and hit the lists button, then clicked on one of the locations and then on "more", the address for the location details view was as follows: http://test.veganaut.net/location/5405ec1c038077c15f0ef539?lat=46.9466881&lng=7.4458981&radius=696

Then I hit "back to the map" and the map address was as follows: http://test.veganaut.net/map?lat=46.9466881&lng=7.4458981&radius=696#zoom:16,coords:46.9473912-7.4458873

then I zoomed in and moved tha map a little and the address read: http://test.veganaut.net/map?lat=46.9466881&lng=7.4458981&radius=696#zoom:18,coords:46.9479845-7.4495137 (i.e. nothing before the #zoom changed)

then I hit the "list" button again and the address of the list-view was as follows:

http://test.veganaut.net/list?lat=46.9478087&lng=7.4495137&radius=174

Why do you keep the previous list coordinates and radius around in the map and location detail adresses?

**Comment by SebuLeugger** [comment]
Also, it should say how many locations were found. (But I guess you'll add this when you limit the number of locations shown by default to 20 and add the "show more" button, just as in the vegan menu list.)

Also, when I entered http://test.veganaut.net/list directly, it showed me a huge list. are those all the locations, from anywhere on the world?

**Comment by SebuLeugger** [comment]
most important point for me: merge the "vegan menu" and "list" buttons as described above and construct the "vegan menu" list based on a radius also (not based on the visible map section, as it is now).

**Comment by toebu** [comment]
First version of this is done, let's close and make more specific tickets for improvements.
