### ISSUE TITLE
location details view: map on top

### ISSUE THREAD

**Issue by SebuLeugger** [veganaut/veganaut#182]
We want the map on top of the location details view, not on the bottom. The name of the location and the offerquality etc. symbols can go on top of the map, like lex suggested, cf. issue #110

**Comment by SebuLeugger** [comment]
Maybe we rather want photos of the location on top (once we have them), or the address. Or a slider, with the map and photos of the location.

**Comment by toebu** [comment]
This is being addressed by a complete redesign of the location page. As this is well under way, I'm closing this.
