### ISSUE TITLE
locations in retirement

### ISSUE THREAD

**Issue by SebuLeugger** [veganaut/veganaut#185]
~~The single most frequent request I get from users (along with requests for a search that also finds veganaut-locations) is to delete particular locations that don't exist any more in real life. I think it's time we implement something soon, or else the data on veganaut will start to be outdated soon. So here's a proposal:~~

~~In the "edit location" view, there's a button/mission which says: "This location doesn't exist (any more)"~~

~~Clicking it opens a menu from which to choose one option:~~
~~- They quit & closed~~
~~- They moved away~~
~~- This location never existed, it was entered by mistake~~

~~Choosing "quit & closed" sets the location to "retired", which means that by default we don't show it any more on the map, by default don't list its offers and products any more in the product browser and by default don't list it any more in the search results (once we show veganaut locations in the search results, that is ;) ). - Later, we can add a checkbox in the filter and search menus (both on the map and in the product browser) which says "show retired locations / show products of retired locations also". If this box is checked, we do as it says, but we e.g. show it in grey instead of black.~~

~~Choosing "they moved away" prompts you to indicate on the map where they moved to, just like in the change coordinates workflow, but there's also a button which says "I don't know where they moved to". Clicking that button just retires the location like above.~~

~~Clicking "never existed" retires the location like above and sets a flag somewhere so that we can check who entered the location, and who said it doesn't exist - this will enable us to do quality control, maybe find trolls or spammers, or maybe find out that it was placed on the wrong coordinates on the map, or something like this.~~

EDIT 3.8.2018: Some of these ideas would still be nice to have, especially giving users the option to search for retired locations also, but we implemented a good enough solution for now: in the edit location view, there appears an additional card at the very bottom where it normally says "this location is still in business" or the like. next to it is an edit-icon. pressing it opens an overlay that lets users choose between "still in business", "permanently closed" and "entered by mistake". The two latter options render the location and its offers invisible on the map, in the lists and in the search, but if someone has the url of the location (e.g. in the browser history) they can still access it. If they do they can read "closed" or "entered by mistake" in red caps in front of the location name. (in the edit view, they can re-activate the location.)

**Comment by SebuLeugger** [comment]
What's also common is that a location changes its name and team and concept. Maybe we should have this as a fourth option:

- they have a new owner/name/concept

Clicking this option retires the old location too and opens a new one at the same position, asking the user only to enter the name of the new place.

**Comment by toebu** [comment]
Most urgent part is done: locations can manually (in the database) be flagged as deleted and they will no longer show up. Flagged 17 locations that said they are closed in the name or description.
Keeping the issue around as there are ideas in here how to make this available to the users.

**Comment by SebuLeugger** [comment]
Mostly done: 

Update 3.8.2018:  Some of these ideas would still be nice to have, especially giving  users the option to search for retired locations also, but we  implemented a good enough solution for now: in the edit location view,  there appears an additional card at the very bottom where it normally  says "this location is still in business" or the like. next to it is an  edit-icon. pressing it opens an overlay that lets users choose between  "still in business", "permanently closed" and "entered by mistake". The  two latter options render the location and its offers invisible on the  map, in the lists and in the search, but if someone has the url of the  location (e.g. in the browser history) they can still access it. If they  do they can read "closed" or "entered by mistake" in red caps in front  of the location name. (in the edit view, they can re-activate the  location.)
