### ISSUE TITLE
Link to homepage of location in all location previews

### ISSUE THREAD

**Issue by SebuLeugger** [veganaut/veganaut#193]
Zueri Vegan suggested that both in the location preview on the map and in the location preview in lists, there should be a button which takes you directly to the location's homepage, if we have the link. This button could be next to the "view location" button.

**Comment by adahyto** [comment]
is it open?

**Comment by adahyto** [comment]
I mean, that I would like to help with it if possible.

**Comment by toebu** [comment]
Awesome! We are currently working on a big update, see the branch release-1-0-0-space-chick-with-be.
I've sent you an e-mail so we can directly discuss how you can help.

**Comment by SebuLeugger** [comment]
We decided to not implement this feature. There are always other issues to work on, though.
