### ISSUE TITLE
Improve the zooming in feature

### ISSUE THREAD

**Issue by alesiom** [veganaut/veganaut#196]
**Context**:
I was in a restaurant in Bern and wanted to grade the restaurant I was in. Although the app enables me to point me to my location, it wasn't clear which part of the map I exactly was. I wanted to zoom more. But zooming too much broke the app. I don't remember super well but guess I was on a poor 3g connexion when it happened. 
I killed the app and tried again - same issue happened. The map kind of freezes or disappears.

I tried to recreate the issue right now with my phone and filmed it. - See attached.

**Observation**:
- It seems like currently there is a maximum zoom value which blocks the user of zooming further (pinching).
- This max value is IMO to large as I wanted to zoom further in to make sure I'm at the right place
- When one reaches this limit and zooms further, it tries to zoom out, but sometimes the map is not displayed anymore.
- With a good wifi connexion, it is far less buggy than with a 3G connexion. It still fails but with a zoom out, I could always regenerate the app easily.

**Further information**:
- iPhone 6
- Default browser, but didn't navigate from it, but directly from the app-icon (I have it on my dashboard)
- iOS version 9.3.3

Since I can't attache a file of more than 10MB, here is a link to the video: http://www.alesiom.ch/share/veganautExample01.mov

**Comment by toebu** [comment]
@alesiom: Can you check if you still have these problems with the latest release? Thanks

**Comment by alesiom** [comment]
@toebu it is definitely much more stable - couldn't repeat the problem. Only remark that might still be interesting to take into account is the second observation - the max offered zoom could be one step more zoomed than the current one is.

**Comment by toebu** [comment]
@alesiom Thanks for checking! Actually the max zoom level is 18 now again. It was 17 for a while because the map tile provider didn't offer a higher resolution. This is the max we can go with OSM and I think it's plenty!
