### ISSUE TITLE
content meta-tag & default-photo for veganaut.net

### ISSUE THREAD

**Issue by SebuLeugger** [veganaut/veganaut#200]
let's define some content meta-tags and set a default-photo for veganaut.net such that people see a nice preview incl. photo when they see a link to a veganaut-page on fb or whatsapp or whatnot.

**Comment by SebuLeugger** [comment]
For the first iteration, this is more or less what we'll add:

<meta name="description" content="Ein Vegan-Guide zum Mitmachen" />
<meta name="abstract" content="Willst du anderen helfen, das vegane Universum zu erkunden? Auf Veganaut.net kannst du vegane Entdeckungen teilen und bewerten." />
<meta name="keywords" content="vegan, shopping, gastro, restaurants, take-away, food, plant-based" />
<meta name="robots" content="follow, index" />

<meta property="og:site_name" content="Veganaut.net" />
<meta property="og:type" content="website" />
<meta property="og:title" content="Veganaut.net" />
<meta property="og:description" content="Ein Vegan-Guide zum Mitmachen" />
<meta property="og:image" content="[lasagne plus logo]" />

**Comment by toebu** [comment]
![veganautbanner](https://cloud.githubusercontent.com/assets/1837568/20107331/6eb3c548-a5d8-11e6-89c9-c8d5989a5191.png)
Here's the image to be used for og:image

**Comment by toebu** [comment]
Done!
