### ISSUE TITLE
Create a dynamic sitemap.xml to submit all pages to search engines

### ISSUE THREAD

**Issue by SebuLeugger** [veganaut/veganaut#201]
what it says in the title

**Comment by SebuLeugger** [comment]
plus: let's have different site titles for different sub-pages of veganaut.net, if possible language-sensitive, if impossible German for the first iteration

homepage: "Ein Vegan-Guide zum Mitmachen - Veganaut.net"
map: "Vegane Weltkarte - Veganaut.net" (ideally dynamic titles such as: "Bern: Vegane Karte - Veganaut.net")
location list: "Locations mit veganen Angeboten - Veganaut.net" (ideally dynamic titles such as "Bern: Locations mit veganen Angeboten - Veganaut.net")
Community: "Community - Veganaut.net"
Login, Register etc.

**Comment by toebu** [comment]
After investigating this, I found that it will be much easier to create a dynamic sitemap (http://www.sitemaps.org/) and submit that to Google.

**Comment by toebu** [comment]
This is done, follow-up in #213.
