### ISSUE TITLE
Add Favorites-Button to embedded map view

### ISSUE THREAD

**Issue by SebuLeugger** [veganaut/veganaut#210]
Replace the "Participate"-button in the embedded map view by a "Favorites"-button of the same colour, but with the pushpin-icon. The button doesn't really do anything yet, we just put it there to see whether visitors press it (more than they pressed the "participate" button, which they only pressed 20 out of 4000 times, roughly).

After pressing the button, visitors are shown a popup (like the search interface in the non-embedded view) which says: 

> 
> Thanks for pushing the "favorites" button. We're counting how many visitors push it to find out whether we should implement this feature. 
> 
> There are sketches of how the favourites feature could look like on our blog. Visit blog.veganaut.net to check them out. 

German: 

> Danke, dass du den "Favoriten"-Knopf gedrückt hast. Wir zählen, wie viele Besucher*innen ihn drücken, um herauszufinden, ob wir dieses Feature implementieren sollen.
> 
> Wie das Favoriten-Feature aussehen könnte, haben wir auf unserem Blog skizziert. Besuche blog.veganaut.net, wenn du es dir anschauen willst.

To close the popup, users should be able to click on an X in the top right corner.

**Comment by toebu** [comment]
Mock is done.
