### ISSUE TITLE
Dedicated page for "Vegan Menu" / product list

### ISSUE THREAD

**Issue by SebuLeugger** [veganaut/veganaut#212]
Pressing "vegan menu" on the map should take me to a dedicated page which lists the vegan options available in that map region. 

This dedicated page could then also be linked to from other places, e.g. the search results: if the search finds a geographical result matching the search query, we could add an additional section which says: "Show vegan products / vegan menu in..." and then the geographical results. Clicking on one of them takes you to the dedicated "vegan menu" page.

**Comment by SebuLeugger** [comment]
It would be great if this list (as well as the locations list) had an embedded mode, too. That way, people on pages with our map embedded on it can stay on the page they are on and still browse this list.

**Comment by toebu** [comment]
Done in release 0.11.0
