### ISSUE TITLE
Fix npm test on Travis

### ISSUE THREAD

**Issue by renestalder** [veganaut/veganaut#226]
It seems like Travis breaks on npm test. Locally the tests seem to run smoothly.

e.g. https://travis-ci.org/veganaut/veganaut/builds/299099326?utm_source=github_status&utm_medium=notification

**Comment by renestalder** [comment]
btw. first break was on 28th of june, see commit overview.
https://github.com/veganaut/veganaut/commits/release-1-0-0-space-chick

**Comment by toebu** [comment]
Fixed. 
@renestalder, @davidsandoz: note that there's a new version of NodeJS being used now (see .nvmrc)
