### ISSUE TITLE
Retrieve new values to show on the map

### ISSUE THREAD

**Issue by davidsandoz** [veganaut/veganaut#232]
On the map view, we now show the total number of restaurants/meals/shops/products and the current radius.

Currently the data is hard coded. This has to be changed to show the correct information.

See the two TODOs at the bottom of [mainMap.tpl.html](https://github.com/veganaut/veganaut/blob/release-1-0-0-space-chick/app/veganaut/map/mainMap.tpl.html).

**Comment by SebuLeugger** [comment]
done
