### ISSUE TITLE
editing completed missions (while visit isn't completed yet)

### ISSUE THREAD

**Issue by SebuLeugger** [veganaut/veganaut#41]
It should be possible to edit completed missions while the visit isn't completed yet, i.e. to add more vegan options that one forgot, or to change the answer for whether there are vegan options from "no" to "yes" or vice versa, if new information comes to light during the visit.

**Comment by SebuLeugger** [comment]
Since we don't have the concept of a "visit" any more, this issue is obsolete. Of course, editing already completed missions still can be an issue, but it's an edge case since most missions can just be repeated at some later time. Also, this hasn't come up in user tests, so it's not important. *close*

**Comment by toebu** [comment]
Actually, it happens quite often that one give the wrong answer especially with the product missions (they submit immediately after you select your answer). So I would keep this around.

**Comment by SebuLeugger** [comment]
this is obsolete. if a user makes a mistake and submits it, he or she can just edit whatever was entered. it will be counted as 2 tasks instead of just 1 which was edited, but that's not such a big deal.
