### ISSUE TITLE
map filter: location type

### ISSUE THREAD

**Issue by SebuLeugger** [veganaut/veganaut#73]
In addition to the "recent" filter we already implemented (cf. #89) we need a location type filter. There are only two location types: gastronomy and retail. The filter should enable users to choose whether they want to see only gastronomy locations, only retail locations, or both. 

User story: When I click on the "Filter map" button a little interface opens which looks like this:
- Filter for last activity
  - [Anytime] [Month] [Week] [Day]
- Filter for location type
  - [All location types] [Gastronomy] [Retail]

..with the "Anytime" and "All location types" options pre-selected, respectively.

The "Filter for last activity" filter (= the "recent" filter in the code) works like it already does, but now on top of that I can 
- click "Gastronomy", which hides all retail locations on the map, or
- click "Retail", which hides all gastronomy locations on the map, and
- click "All location types" again, which makes both gastronomy and retail locations visible again on the map.

When I close that little interface after having chosen my filter settings the filter(s) remain active and the "Filter" button shows that it is activated (unless both the "Anytime" and the "All location types" options were chosen respectively, of course).

**Comment by judenaveenraj** [comment]
@SebuLeugger  : Hi i have cloned the project and completed this feature. Get in touch with me at judenaveenraj@gmail.com before i send a pull request.
