### ISSUE TITLE
let users (dis)confirm vegan options entered by others

### ISSUE THREAD

**Issue by SebuLeugger** [veganaut/veganaut#75]
maybe once we have implemented the vegan options classifications (cf. #60) this will not be important any more because our data will be structured enough for us to be able to provide sufficiently good info without constant (dis)confirmation, but I'm still putting it here because we closed a larger issue that contained this feature request before we could implement it (cf. #40)

**Comment by filodoofus** [comment]
I'm seconding this issue. It should be easier to delete options for the users since things might change rather radically and quickly. For instance, take a look at the following screenshot.
![untitled](https://cloud.githubusercontent.com/assets/4923022/5681457/024cda8a-9819-11e4-89de-9cb27faa753b.png)
Several of these options are not available anymore due to a change in establishment.

**Comment by SebuLeugger** [comment]
We decided not to implement classifications of vegan options but instead just add a plain text description attribute to every option, and let users decide whether the options should be (temporarily or permanently) removed from the list of available options. 

That is, the whatOptions mission should be modified as follows:

- [concerns design only] the list of already entered options within the whatOptions mission should use the same list style as the list of available options in the regular location details view.
- [concerns functionality] each item on the list gets two buttons: a REMOVE button (on the left) and a CONFIRM button (on the right). 
  - clicking the REMOVE button makes two more buttons appear: [for now]  [forever]
    - clicking [for now] makes an option list appear: "Available again [in a few hours; tomorrow; in a few days; in a few weeks; in a few months; later; don't know]"
    - clicking [forever] makes an option list appear: "This product [will never available again; is a duplicate/irrelevant entry; is SPAM (flag the person who entered this as a potential troll)]"
  - clicking CONFIRM confirms the option. 

Temporarily removed options are still shown in the product list, but with some indication that they're currently unavailable (maybe along with the date of the last info along with the info given then, e.g. "XYZ said on 13.1.15 that it will be available again in a few days") 

Permantently removed options that aren't spam or duplicate/irrelevant are kept in the location history (that users might be able to look at by pushing some button one day; implementing this is not part of this issue)

Permanently removed options that are spam or duplicate/irrelevant are removed from the database and if they're spam the people who entered them and/or confirmed them are flagged somehow (implementing this is not part of this issue)

**Comment by SebuLeugger** [comment]
If we add both the "delete this option because it is spam (and flag the person who entered this option as a potential troll)" option and the "edit option name & option description" option we have to finde a solution to this problem: The person who originally entered the option might have entered a genuine option, so isn't a troll at all, but then someone else might later have edited the option name & description in a way that turns the whole thing into spam. We obviously want to flag the latter person as a potential troll, not the former. How can we do this?

One obvious part of the solution is to implement an option history that logs every change together with the author of that change (like in the history of an article on wikipedia). Should users be able to browse the option history at all times or should we e.g. only show them the history when they say the option is spam, and then ask them to specify whether it was spam from the start or because of some more recent edit? I don't know.

**Comment by SebuLeugger** [comment]
This is getting more acute now that some of the data are a few months old. E.g. https://veganaut.net/location/543553cd509d9b885f03bed6 doesn't have vegan sandwiches any more and https://veganaut.net/location/5435525b509d9b885f03beaf offers more than 1 vegan menu per week now. Dänu wanted to change that and couldn't. Maybe you can do it manually for now, @toebu

**Comment by toebu** [comment]
I'm working on a suggestion for how this might look like (along with other missions related to products)

What do you think?
![editproduct](https://cloud.githubusercontent.com/assets/1837568/7866283/da60d8b4-056e-11e5-98a2-aa872f0f8f54.png)

**Comment by SebuLeugger** [comment]
I think one line with a rating is enough. If the user hasn't rated this item then just show the average rating and put a button next to it: [Rate] - Clicking that button replaces the stars displaying the average rating with the stars that let me choose my rating and then click on either [Cancel] or [Done]. If you click done you now see MY rating (clearly marked as such), because I care about how I rate stuff, not about how others rate it (my taste may be different). Next to the "My rating" title there could be two buttons [Show average rating] and [change my rating]. If I click on the first the title changes to "average rating by all veganauts", with the two buttons [show my rating] and [rate] next to it. By default, I would want to see MY rating of items, no? 

Anyway, let's talk about this whole thing in person.

**Comment by toebu** [comment]
Branch edit-products was now merged and this is done.
A few texts have to be translated to French:
- showUnavailableProducts
- showAllMissions
- verify everything under rateProduct
- setProductName
- setProductAvail
- product (rating/availability)

**Comment by SebuLeugger** [comment]
translation: done.
