### ISSUE TITLE
text description for a new activity link

### ISSUE THREAD

**Issue by xabbu42** [veganaut/veganaut#8]
It would be nice if I could describe the activity I did in free form text if I want to.

Advantages:
  * my graph gets a more personal flavour

    For example I'll see if one of my friends cooks a lot, or buys fruit or whatever this particular player does different from others.

  * cheating is a little bit more involved (their is some pressure to actively invent a description)

  * moar data (like popular foods...)

**Comment by SebuLeugger** [comment]
We kind of decided that we won't re-introduce the social graph as an actual graph, so we most likely won't re-introduce activity links as such either.
