### ISSUE TITLE
wheather icons for effortValue ratings

### ISSUE THREAD

**Issue by SebuLeugger** [veganaut/veganaut#80]
We decided to use wheather icons for the effortValue ratings. I guess you can use this font: http://erikflowers.github.io/weather-icons/ (it's optimized for bootstrap)

suggestions:

yes: wi-day-sunny
ratherYes: wi-day-cloudy
ratherNo: wi-cloudy
no: wi-thunderstorm

These icons should go into the effortValue mission answers (analogously to the offerQuality symbols in the offerQuality mission answers), and the average effortValue rating of a location should go as a weather icon next to the average offerQuality rating (after the location name in the location details view). The hover text for this symbol should read: "The fairer the whether the better the chances that the vegan offer will improve if more veganauts come here. Average 3.1, Number of ratings 4"

**Comment by toebu** [comment]
If you have time to look into this, please implement it in a separate branch.

**Comment by phoppen** [comment]
As opposed to offerQuality, a String has been used here. Since we're about to calculate averages, we should use a numeric scale here, too. Do we need some kind of migration script for the database?

**Comment by toebu** [comment]
Actually the answer strings are already [mapped to a numerical value](https://github.com/veganaut/veganaut-backend/blob/master/app/models/Location.js#L22). To get the average to the frontend, you probably just have to extend the [JSON transform method](https://github.com/veganaut/veganaut-backend/blob/master/app/models/Location.js#L176.
) of the Location model.

One little gotcha: the [Average](https://github.com/veganaut/veganaut-backend/blob/master/app/utils/Average.js) automatically uses the plural form of the field name to store the values in the db. So to get the current average value, you have to access `efforts.average`.

**Comment by phoppen** [comment]
Thanks. Wouldn't it make more sense for ratherNo to have value -0.5 instead of 0.5?

**Comment by toebu** [comment]
Oh, that's a bug indeed. That means we will also have to recalculate all average values based on the mission answers. If you want to take a stab at that db upgrade script, you can check similar ones in the backend repo in the migrations folder.

On February 8, 2015 12:51:00 PM CET, phoppen <notifications@github.com> wrote:
>Thanks. Wouldn't it make more sense for ratherNo to have value -0.5
>instead of 0.5?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/veganaut/veganaut/issues/80#issuecomment-73407621

-- 
Tobias Leugger
Schänzlihalde 30
3013 Bern
Switzerland
Mobile: +41 79 822 27 03

**Comment by phoppen** [comment]
weathericons stuff is committed in separate branch. For the migration script: I get the idea but I'm not exactly sure how to execute migration scripts and how to validate that it worked. If it's a pressing issue, I guess you're more efficient doing it. Otherwise, I'll appriciate some hints.

**Comment by toebu** [comment]
Looks good, I just have a couple of suggestions:
- I would not show the weather icon next to the name of the locations if there haven't been any ratings yet
- The weather icons are on Bower: http://bower.io/search/?q=Weather%20Icons. It would be better if you add them to bower.json and load them directly from the app/lib/... folder

For the migration script: I can take care of it. I won't be able to work on Veganaut for one week now however. If you want to look into it: the migrations can be run by calling the mongo executable and giving it the name of the DB and then the script:
`mongo veganaut veganaut-backend/migrations/...js`
While you are working on the migration script you can use `print` and `printjson` to print what you are working with. You can use the interactive mongo terminal to look at what you changed: `mongo veganaut` and then mongo db commands. Finally, you can reload the fixtures to get back to the initial state with `node ./veganaut-backend/test/fixtures/basic.js` (although there might be no efforValue mission in these fixtures, then you can add them through the frontend).

I'll check in a week if you had time to do work on this further. If not it's of course not a problem.

**Comment by phoppen** [comment]
Now the weather-icons are controlled by bower and the icon for the average is not shown when no respective mission has been done. ratherNo is now -0.5, and there is a migration script to recalculate location.effort.total. :-)

**Comment by toebu** [comment]
Thank you very much and sorry for not having merged this yet. I'm not finding any time at the moment for coding on Veganaut. Will get better from beginning of March on.
