### ISSUE TITLE
"What's New?" Map Filter

### ISSUE THREAD

**Issue by SebuLeugger** [veganaut/veganaut#89]
As a first version of something like a news feed, let's implement a map filter that only shows locations

- which either were newly added
- or at which new missions were completed at

since the user was last logged in. (Visitors of the site who don't have a login who use that filter are just shown all the changed locations since e.g. 1 week ago.)

User story: There's a button at the top, next to the "add new location" button, which reads: "Filters". When I click that button I can somehow choose the filters I want to apply to the map (c.f. e.g. how they do it on mapsearch.ch (mobile version)), which for now is just one single option called "What's new?". When I have chosen that option, I can either click "cancel" or "apply filters". When I click either of those buttons I'm back on the map which shows the appropriate locations.

**Comment by toebu** [comment]
This first version is deployed and can be tested.

**Comment by SebuLeugger** [comment]
great! it works like it should most of the time. those are the issues I had:
- the map doesn't load properly on my phone's browser (firefox for android) when I open the browser, it just shows a uniformly grey field. I have to click refresh, then it works. (not sure whether this has anything to do with the filter, but it never happened before)
- at one time when I had the "week" filter set and then clicked on locations the preview of the location didn't show at all, or only showed very briefly and then disappeared again. 
- when I set a filter and then view a location and then go back to the map the filter isn't set any more. I think it should remember the filter settings on the map.

**Comment by SebuLeugger** [comment]
Also, the filters should be available for visitors who are not logged in. (just put the filter button next to the register and login buttons, or get rid of the register and login buttons (they can be accessed via the burger anyway))
