### ISSUE TITLE
location history

### ISSUE THREAD

**Issue by SebuLeugger** [veganaut/veganaut#90]
Because some users like to know what exactly happened at what location recently let's add a "mission history" button somewhere in the location view. When I push that button I'm shown a list of the missions that have been completed at this location, with the newest missions at the top. 

The information available about the individual missions are these:

- type of mission (the original "add location" mission is also one of the mission types we show here)
- result of mission (like the summary that you get after you just completed a mission)
- how many points were made with the mission for what team
- a "new" tag indicating that the tagged mission was completed only since the last time the user had been logged in.

I'm unsure whether we should provide the following information:

- the player who completed the mission (nickname) (I'm leaning towards showing this, because it makes the whole thing more meaningful to most users if they see concrete people behind the missions)
- the day of completion (I don't think that's necessary and in combination with the above item it would be a bit problematic privacy-wise. So I'm leaning towards not showing this.)

Anyway, the list I'm shown after pushing the button should probably just show the mission type and the team the points were awarded to, plus the "new" tag. The rest of the info I only get once I expand that mission.

**Comment by toebu** [comment]
Not at all what we initially planned, but good enough for now. Should be easy to add more details since the backend already provides the full list of recent missions.
