### ISSUE TITLE
current user rating of options does not reset after cancelling the mission

### ISSUE THREAD

**Issue by filodoofus** [veganaut/veganaut#92]
It would be good if the ratings for options would reset (before the user saves the mission) if the mission is cancelled. For instance, I might accidentally rate an item that I haven't tried. There is as of yet no possibility to undo this (without leaving the location all together). The most intuitive move would be to cancel the mission, but the ratings stay there if you try again.

Maybe this is related to issue #41.

**Comment by toebu** [comment]
Should be easy enough to make the mission reset correctly when aborting it.
