### ISSUE TITLE
Product Browser

### ISSUE THREAD

**Issue by SebuLeugger** [veganaut/veganaut#95]
Here's a proposal for how we could implement a product browser (beside the obvious solution of just entering the name of a product in the search field, which I think we should implement as well at some point):

Have a button (e.g. with a leaf-symbol like icon-leaf here: https://marcoceppi.github.io/bootstrap-glyphicons/ (Why a leaf? Because it's what grows on a twig, and the locations are sybolised by plants with 1 to 5 twigs. Alternatives to leaves would be e.g. fruit icons, but I like the leaf better because fruits suggest sweet food, whereas the leaf just stands for plant food.)) next to the search  and filter buttons on the map. Pressing that button opens a list of products available at the locations currently visible on the map, ordered e.g. from highest-rated to lowest-rated (alternative: most-bought to least-bought, most-often-rated to least-often-rated, or a combination of these). Maybe it's best to make the list complete (i.e. it contains all the options offered at the locations visible on the map) or maybe it's better to just show the top ten or so, with a "show more" button or the like. 

Two things should be possible to do with the list:

a) going directly from an option to the location view of the location where it's available at

~~b) selecting one or more options and then going back to the map by pressing a button called e.g. "show on the map". The map now only shows the locations where at least one of the selected options is available at (use case: "I'd like to eat either that, or that, or that. Let's see where where I'd have to go to get this...").~~

~~Option b) amounts to a customizable map filter (which would be orthogonal to the regular filters).~~ [Edit: I don't think we need this / it might be too unfamliar and complicated to be useful.]

What do you guys think of this?

**Comment by toebu** [comment]
Created two follow up tickets #107, #108 to implement this.
